### ISSUE TITLE
Rewrite plan

### ISSUE THREAD

**Issue by notmymonkeys** [lm-tools/work-you-could-do-node#2]
This outlines the work that will need to be completed in order to replace current rails app with node

- [x] Introduction page -  PR #3 
- [x] Create uuid and redirect - PR #4
- [x] Search page - PR #5 PR #6
- [ ] Role details page
- [ ] Save role
- [ ] Saved roles page
- [ ] Remove role from saved 
- [ ] `How do I use this?` page
- [ ] Breadcrumbs
- [ ] Google tag manager
- [ ] Infra

**Comment by chilliwilly77** [comment]
This is now maintained under Jira epic: https://projects.digital.uc.dwp.gov.uk/browse/OR-1159
